services:

    proximity_active_directory_user.user_provider:
        class: Proximity\ActiveDirectoryUserBundle\Security\User\ActiveDirectoryUserProvider

    proximity_active_directory_user.authenticator:
        class:     Proximity\ActiveDirectoryUserBundle\Security\ActiveDirectoryAuthenticator
        calls:
            - [ setHost, [ %proximity_active_directory_user.ldap_host% ] ]
            - [ setOrganizationalUnit, [ %proximity_active_directory_user.organizational_unit% ] ]
            - [ setDomainComponents, [ %proximity_active_directory_user.domain_components% ] ]