parameters:
    proximity_active_directory_user.authenticator.class: Proximity\ActiveDirectoryUserBundle\Security\ActiveDirectoryAuthenticator
services:
    proximity_active_directory_user.authenticator:
        class: %proximity_active_directory_user.authenticator.class%
        calls:
            - [ setHost, [ %proximity_active_directory_user.ldap_host% ] ]
            - [ setOrganizationalUnit, [ %proximity_active_directory_user.organizational_unit% ] ]
            - [ setDomainComponents, [ %proximity_active_directory_user.domain_components% ] ]