services:
    proximity_ldap_user.user_provider:
        class: Proximity\LdapUserBundle\Security\User\LdapUserProvider

    proximity_ldap_user.authenticator:
        class:     Proximity\LdapUserBundle\Security\LdapAuthenticator
        calls:
            - [ setHost, [ %ldap_host% ] ]